permalink: /:year/:month/:day/:title.html
rouge: true


# 作者信息
author:
  name: Yhspehy
  email: yhspehy@gmail.com

# 使用 markdown 格式
markdown: kramdown
redcarpet:
  extensions: ["tables", "highlight"]

# disqus 设置
disqus:
  shortname: Yhspehy

port: 4010
